bases:
- git::https://repo1.dso.mil/platform-one/big-bang/bigbang.git//base?ref=1.53.0
configMapGenerator:
  - name: environment
    behavior: merge
    files:
      - values.yaml=configmap.yaml
  - name: common
    behavior: merge
    files:
      - values.yaml=configmap.yaml
patchesStrategicMerge:
- |-
  apiVersion: source.toolkit.fluxcd.io/v1beta2
  kind: GitRepository
  metadata:
    name: bigbang
  spec:
    interval: 1m
# Use the following three lines to test a new version of Big Bang without affecting other environments
   # ref:
   #   $patch: replace
   #   tag: "1.53.0"
- |-
  apiVersion: helm.toolkit.fluxcd.io/v2beta1
  kind: HelmRelease
  metadata:
    name: bigbang
  spec:
    interval: 1m
